# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js + Vite app to Azure Web App - rsms

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Install & build frontend
      - name: Install and build frontend
        working-directory: ./client
        run: |
          npm install
          npm run build

      # Install backend deps
      - name: Install backend dependencies
        working-directory: ./server
        run: npm install

      # Move frontend dist into server/public (adjust if different)
      - name: Move frontend build to backend
        run: |
          mkdir -p server/public
          cp -r client/dist/* server/public/

      # Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./server

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rsms'
          slot-name: 'Production'
          package: .


          
